#pragma once
#include "stdafx.h"

#define REG_DECLARE "declare"
#define REG_STRING "string"
#define REG_INTEGER "integer"
#define REG_FUNCTION "function"
#define REG_RETURN "return"
#define REG_PRINT "print"
#define REG_MAIN "main"
#define REG_ID "[a-z]+"
#define REG_INTEGER_LIT "[0-9]+"
#define REG_STRING_LIT "'(.)*'"
#define REG_SEMICOLON ";"
#define REG_EQUAL "="
#define REG_COMMA ","
#define REG_MREQUAL "\\{"
#define REG_LSEQUAL "\\}"
#define REG_LEFTTHESIS "\\("
#define REG_RIGHTTHESIS "\\)"
#define REG_PLUS "\\+"
#define REG_MINUS "\\-"
#define REG_STAR "\\*"
#define REG_DIRSLASH "/"
#define REG_STRLEN "strlen"
#define REG_SUBSTR "substr"